// Generated by CoffeeScript 1.6.3
(function() {
  var Drone;

  Drone = (function() {
    function Drone(eventemitter, client) {
      this.eventemitter = eventemitter;
      this.client = client;
      this.eventemitter.on('takeoff', function() {
        return this.client.takeoff(function() {
          return this.eventemitter.emit('inflight');
        });
      });
      this.eventemitter.on('land', function() {
        return this.client.land(function() {
          return this.eventemitter.emit('ready');
        });
      });
    }

    return Drone;

  })();

  module["export"] = Drone;

}).call(this);
